// Copyright 2022 sporkus
// SPDX-License-Identifier: GPL-2.0-or-later
#pragma once

#define WS2812_DI_PIN A15
#define RGB_MATRIX_LED_COUNT 11
#define DRIVER_LED_TOTAL RGB_MATRIX_LED_COUNT

#define RGB_MODS_INDICATOR_ENABLE
#define RGB_LAYER_INDICATOR_ENABLE
#define RGB_FRONT_BRIGHTNESS_SCALE 3

#define RGB_MATRIX_FRAMEBUFFER_EFFECTS
#define RGB_MATRIX_KEYPRESSES
#define RGB_TRIGGER_ON_KEYDOWN
#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 255
#define RGB_MATRIX_HUE_STEP 8
#define RGB_MATRIX_SAT_STEP 8
#define RGB_MATRIX_VAL_STEP 8
#define RGB_MATRIX_SPD_STEP 16
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_CYCLE_ALL
#define RGB_MATRIX_DEFAULT_HUE 0
#define RGB_MATRIX_DEFAULT_SAT 255
#define RGB_MATRIX_DEFAULT_VAL 100
#define RGB_MATRIX_DEFAULT_SPD 32

#define ENABLE_RGB_MATRIX_CYCLE_ALL
